import type { Kit, Question } from "../pipeline/types.js";

const CATEGORY_LABELS: Record<Question["category"], string> = {
  technical: "Technical",
  behavioural: "Behavioural",
  "system-design": "System design",
  "company-fit": "Company fit",
};

const DIFFICULTY_LABELS: Record<number, string> = { 1: "Easy", 2: "Medium", 3: "Hard" };

/**
 * Renders a finished kit as a self-contained Markdown study sheet.
 *
 * Deliberately a pure string transform of the already-validated kit rather than a fresh
 * LLM call: an export must reproduce exactly what the user edited and pinned in the
 * builder, so there is nothing for a model to add here. Markdown (rather than PDF) keeps
 * the backend dependency-free and gives the user something they can paste into Notion,
 * Obsidian, or a GitHub gist and keep editing.
 */
export function kitToMarkdown(kit: Kit): string {
  const out: string[] = [];
  const line = (s = "") => out.push(s);

  line(`# Interview prep: ${kit.role.title || "Untitled role"}`);
  line();
  line(`**Company:** ${kit.source.company || "Unknown"} — <${kit.source.company_url}>  `);
  if (kit.role.seniority) line(`**Seniority:** ${kit.role.seniority}  `);
  if (kit.source.location) line(`**Location:** ${kit.source.location}  `);
  line(`**Researched:** ${kit.source.researched_at}  `);
  line(`**Prep window:** ${kit.schedule.days_available} day(s)`);
  line();
  line("---");
  line();

  line("## Company brief");
  line();
  line(kit.company_brief.summary || "_No summary available._");
  line();
  if (kit.company_brief.what_they_do) {
    line("**What they do**");
    line();
    line(kit.company_brief.what_they_do);
    line();
  }
  if (kit.company_brief.hiring_process_notes) {
    line("**How they interview**");
    line();
    line(kit.company_brief.hiring_process_notes);
    line();
  }
  if (kit.company_brief.sources.length) {
    line("**Sources**");
    line();
    for (const src of kit.company_brief.sources) line(`- <${src}>`);
    line();
  }

  line("## The role");
  line();
  if (kit.role.responsibilities.length) {
    line("**Responsibilities**");
    line();
    for (const r of kit.role.responsibilities) line(`- ${r}`);
    line();
  }

  const uncovered = new Set(kit.coverage.uncovered_requirement_ids);
  line("**Requirements**");
  line();
  line("| # | Requirement | Kind | Priority | Covered |");
  line("|---|---|---|---|---|");
  for (const req of kit.role.requirements) {
    const covered = uncovered.has(req.id) ? "No" : "Yes";
    line(`| ${req.id} | ${escapeCell(req.text)} | ${req.kind} | ${req.priority} | ${covered} |`);
  }
  line();

  line("## Question bank");
  line();
  const byId = new Map(kit.role.requirements.map((r) => [r.id, r.text]));
  for (const category of Object.keys(CATEGORY_LABELS) as Question["category"][]) {
    const questions = kit.questions.filter((q) => q.category === category);
    if (!questions.length) continue;
    line(`### ${CATEGORY_LABELS[category]} (${questions.length})`);
    line();
    questions.forEach((q, i) => {
      line(`**${i + 1}. ${q.prompt}**`);
      line();
      line(`_Difficulty: ${DIFFICULTY_LABELS[q.difficulty] ?? q.difficulty}_`);
      line();
      line(`How to answer: ${q.answer_outline}`);
      line();
      const linked = q.requirement_ids.map((id) => byId.get(id)).filter(Boolean);
      if (linked.length) {
        line(`Covers: ${linked.join("; ")}`);
        line();
      }
    });
  }

  line("## Flashcards");
  line();
  kit.flashcards.forEach((card, i) => {
    line(`**${i + 1}. ${card.front}**`);
    line();
    line(card.back);
    line();
  });

  line("## Study schedule");
  line();
  const questionById = new Map(kit.questions.map((q) => [q.id, q]));
  for (const day of kit.schedule.days) {
    line(`### Day ${day.day} — ${day.focus} (${day.minutes} min)`);
    line();
    if (!day.question_ids.length) {
      line("_Review / buffer day — no new material scheduled._");
      line();
      continue;
    }
    for (const qid of day.question_ids) {
      const q = questionById.get(qid);
      if (q) line(`- [ ] ${q.prompt} _(${CATEGORY_LABELS[q.category]}, ${DIFFICULTY_LABELS[q.difficulty]})_`);
    }
    line();
  }

  line("---");
  line();
  line("_Generated by the AI Interview Prep Kit._");

  return out.join("\n");
}

/** Pipes and newlines would break out of a Markdown table cell. */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\|").replace(/\s*\n\s*/g, " ").trim();
}

/** A filesystem-safe, descriptive download name, e.g. `acme-senior-backend-engineer-prep.md`. */
export function exportFilename(kit: Kit, extension: string): string {
  const slug = [kit.source.company, kit.role.title]
    .filter(Boolean)
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return `${slug || "interview-prep-kit"}-prep.${extension}`;
}
